site_name: Avalon Reveries

nav:
  - Home: index.md
  - Release Notes: release_notes.md
  - Avalon:
    - Overview: avalon_overview.md
    - Launcher: avalon_launcher.md
    - Tools:
      - Project Manager: avalon_tool_project_mgr.md
      - Context Manager: avalon_tool_context_mgr.md
      - Work Files: avalon_tool_workfiles.md
      - Creator: avalon_tool_creator.md
      - Publish: avalon_tool_publish.md
      - Loader: avalon_tool_loader.md
      - Scene Inventory: avalon_tool_scene_mgr.md
  - Publish:
    - Overview: publish_overview.md
    - Maya:
      - Overview: publish_maya.md
      - Render: publish_maya_render.md
    - Houdini: publish_houdini.md
    - Nuke:
      - Overview: publish_nuke.md
      - Render: publish_nuke_write.md
  - Utilities:
    - Overview: utilities_overview.md

theme:
  name: 'material'
  font:
    text: 'Noto Sans TC'
    code: 'Roboto Mono'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  feature:
    tabs: true

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/doc.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
