schema = "avalon-core:config-1.0"

[[apps]]
name = "maya2018"
label = "Maya 2018"

[[apps]]
name = "houdini18"
label = "Houdini 18"

[[tasks]]
name = "modeling"

[[tasks]]
name = "rigging"

[tasks.options.autoModelUpdate]
label = "Auto update model"
default = false
help = "Auto update model to latest version after model publish."

[[tasks]]
name = "lookdev"

[[tasks]]
name = "charFX"

[[tasks]]
name = "crowdFX"

[[tasks]]
name = "FX"

[[tasks]]
name = "setdressing"

[[tasks]]
name = "animating"

[[tasks]]
name = "layout"

[[tasks]]
name = "lighting"

[[tasks]]
name = "compositing"

[template]
# Arg {user} been removed.
# To re-implement {user} into path, better work file management tool is required.
work = "{root}/{project}/Avalon/{silo}/{asset}/work/{task}/{app}"
publish = "{root}/{project}/Avalon/{silo}/{asset}/publish/{subset}/v{version:0>3}/{representation}"


[[groups]]
name = "Trash Bin"
icon = "trash-o"
color = "#C4CEDC"
order = -99

[[groups]]
name = "USD"
icon = "file-text-o"
color = "#C4CEDC"
order = -80

[[groups]]
name = "Renders"
icon = "server"
color = "#22EAAA"
order = 10


# Family name should be lower case

[[families]]
name = "reveries.shotpkg"
label = "Shot Package"
icon = "shopping-basket"

[[families]]
name = "reveries.write"
label = "Write"
icon = "ticket"

[[families]]
name = "reveries.renderlayer"
label = "Render Layer"
icon = "server"

[[families]]
name = "reveries.model"
label = "Model"
icon = "cubes"

[[families]]
name = "reveries.xgen"
label = "XGen"
icon = "paw"

[[families]]
name = "reveries.xgen.legacy"
label = "XGen Legacy"
icon = "paw"
hideFilter = true

[[families]]
name = "reveries.xgen.interactive"
label = "XGen Interactive"
icon = "paw"
hideFilter = true

[[families]]
name = "reveries.rig"
label = "Rig"
icon = "sitemap"

[[families]]
name = "reveries.look"
label = "Look"
icon = "paint-brush"

[[families]]
name = "reveries.texture"
label = "Texture"
icon = "picture-o"

[[families]]
name = "reveries.setdress"
label = "Set Dress"
icon = "tree"

[[families]]
name = "reveries.animation"
label = "Animation"
icon = "male"

[[families]]
name = "reveries.pointcache"
label = "Point Cache"
icon = "diamond"

[[families]]
name = "reveries.pointcache.abc"
label = "Point Cache"
icon = "diamond"
hideFilter = true

[[families]]
name = "reveries.pointcache.gpu"
label = "Point Cache"
icon = "diamond"
hideFilter = true

[[families]]
name = "reveries.pointcache.fbx"
label = "Point Cache"
icon = "diamond"
hideFilter = true

[[families]]
name = "reveries.camera"
label = "Camera"
icon = "video-camera"

[[families]]
name = "reveries.lightset"
label = "Light Set"
icon = "lightbulb-o"

[[families]]
name = "reveries.standin"
label = "Arnold Stand-In"
icon = "coffee"

[[families]]
name = "reveries.atomscrowd"
label = "Atoms Crowd"
icon = "building"

[[families]]
name = "reveries.mayashare"
label = "Maya Share (.ma)"
icon = "share-square-o"

[[families]]
name = "reveries.vdbcache"
label = "VDB Cache"
icon = "qrcode"

[[families]]
name = "reveries.look.asset_prim"
label = "USD (Asset)"
icon = "list"

[[families]]
name = "reveries.ani.ani_prim"
label = "USD (Ani)"
icon = "list"

[[families]]
name = "reveries.look.pre_prim"
label = "Look PrePrim USD"
icon = "paint-brush"
hideFilter = true

[[families]]
name = "reveries.look.usd"
label = "Look USD"
icon = "paint-brush"
hideFilter = true

[[families]]
name = "reveries.model.usd"
label = "Model USD"
icon = "cubes"
hideFilter = true

[[families]]
name = "reveries.pointcache.usd"
label = "Pointcache USD"
icon = "diamond"
hideFilter = true
